version: 2.1

executors:
  default:
    docker:
      - image: circleci/openjdk:11-jdk

jobs:
  build:
    executor: default
    steps:
      - checkout

      # You can add any necessary steps here for building your project
      # For example, if you're using Gradle Wrapper, you might use the following step:
      - run:
          name: Build Project
          command: |
            chmod +x gradlew
            ./gradlew build

  test:
    executor: default
    steps:
      - checkout

      # Start the Selenium Grid and browser nodes using Docker Compose
      - run:
          name: Start Selenium Services
          command: docker-compose -f .circleci/docker-compose.yml up -d

      # Run your Selenium tests using Gradle with the proper system properties
      - run:
          name: Run Selenium Tests
          command: |
            chmod +x gradlew
            ./gradlew test -Dselenium.remote.url=http://localhost:4444/wd/hub

      # Stop the Selenium services after tests are done
      - run:
          name: Stop Selenium Services
          command: docker-compose -f .circleci/docker-compose.yml down

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
