version: 2.1
executors:
  default:
    docker:
      - image: circleci/openjdk:11-jdk
jobs:
  build:
    docker:
      - image: circleci/openjdk:11-jdk
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: |
            sudo apt-get update && sudo apt-get install -y chromium-browser
            curl -sL https://deb.nodesource.com/setup_12.x | sudo -E bash -
            sudo apt-get install -y nodejs
            npm install -g chromedriver
      - run:
          name: Build Project
          command: ./gradlew assemble
      - persist_to_workspace:
          root: .
          paths:
            - build/
            - gradle/
  test:
    docker:
      - image: circleci/openjdk:11-jdk
    steps:
      - checkout
      - attach_workspace:
          at: /tmp/workspace
      - run:
          name: Run Selenium Tests
          command: ./gradlew clean test --tests LoginRunner
workflows:
  version: 2
  build-test:
    jobs:
      - build
      - test:
          requires:
            - build
